### ISSUE TITLE
Is mopidy-leftasrain still working?

### ISSUE THREAD

**Issue by lukiasz** [naglis/mopidy-leftasrain#3]
Hello!

When I run `mopidy leftasrain pull`, I get:

`ERROR    Fetch failed: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy_leftasrain/remote.py", line 143, in _       fetch_song
    result = urllib2.urlopen(url, timeout=self._timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)`

It tries to reach `http://leftasrain.com/getNextTrack.php?shuffle=false&currTrackEntry=0` which is not available.

**Comment by naglis** [comment]
Hi @lukiasz, 

I am so sorry for taking so long to respond but somehow I did not notice this issue.

The guys at leftasrain have changed the way they serve the song MP3s, so now it's required to acquire a time-limited token each time you wan't to play the song. This makes it much harder to implement it as a Mopidy plugin, and I am not really sure it's worth it.

However, I have a minimal Python [script](https://github.com/naglis/leftasrain) which you could use to stream songs one by one.

I'll update the README to mark this as broken and also make a PR to Mopidy to remove this plugin from documentation.
